title: Katherine Manning # your name (or website title) here
logo: "https://i.gyazo.com/ca5c77f11d77196fedcff6a922831e1f.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I'm Katherine or Kat, welcome to my Portfolio. 
  <br><br>
  I'm a hardworking Manager and Data Analyst focused on completing work quickly to consistently exceed targets. 
  A reliable team member and leader accustomed to taking on challenging tasks. 
  I'm dedicated to business success and analyzing information. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
