title: Katherine Manning # your name (or website title) here
logo: "https://i.gyazo.com/7097a56479d0c130695f8c0b44ce96b9.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I'm Katherine or Kat, welcome to my Portfolio. 
  <br><br>
  I'm a hardworking Manager and Data Analyst focused on completing work quickly to consistently exceed targets. 
  A reliable team member and leader accustomed to taking on challenging tasks. 
  I'm dedicated to business success and analyzing information. 
  <br><br>
  Skills:<br>
 - Networking and collaboration
- Budgeting and cost control
- Attention to detail
- Verbal communication
- Problem-solving
- Multitasking
- Model data
- Industry research
- Analyze trends
- Competitive analysis<br><br>
Technical Skills:<br>
- Python
- Javascript
- Matplotlib
- Pandas
- Plotly
- PostgreSQL
- SQLAlchemy
- Microsoft Office Suite
- Git Bash
- Google API
- MongoDB <br><br><br>
  <a href="https://www.linkedin.com/in/kittlekaboot/">View My LinkedIn Profile</a> <BR><BR><BR>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
