title: "Katherine Manning" # your name (or website title) here
logo: "https://i.ibb.co/1G7XCkb/20201030-133206.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Aspiring developer
  
  
  Experience in Customer Service, Retail Management, Administrative Assistant, Data Analytics, and Data Entry.
  Currently pursuing an A.S in Computer Programming - 2022
  <br><br><br><br>
  
  <a href="https://www.linkedin.com/in/katmanning00/">View My LinkedIn Profile</a> <br><br>
  <a href="mailto:kat.m.manning94@gmail.com">Email Me</a>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
